#!/usr/bin/perl -w
use strict;
use feature ":5.10";
use warnings FATAL => 'all';

my $inData = 0;

while (<STDIN>) {
	chomp (my $line = $_);
	if (!$inData) {
		if ($line =~ /^data:\s*/) {
			$inData = 1;
		}
		next;
	}

	if ($line !~ /^\s+/) {
		# No longer in the data - exit
		exit 0;
	}

	if ($line !~ /^\s*([^:]+):\s(.+)$/) {
		say STDERR "Wrong format for the entry: $line";
		exit 1;
	}

	my $key = $1;
	my $value = $2;
	my $decoded = `echo "$value" | /usr/bin/base64 --decode`;

	#say "key = $key, value = $value";
	say "===============================================================";
	say "$key:";
	say "$decoded";
	say "===============================================================";
}
